### ISSUE TITLE
Ne sprema podatke za e-mail

### ISSUE THREAD

**Issue by Doda89vk** [coax/solo-for-woocommerce#1]
Pozdrav,

Označim da "automatsko slanje", te popunim naslov e-maila kao i poruku, ali nakon što spremim prikaže da je spremljeno, ali polja budu prazna.

btw jedno pitanje, dali se način plaćanja može dodati od plugina koji većinom mi iz Hrv koristimo za kreiranje uplatnica (https://wordpress.org/plugins/croatian-payment-slip-generator-for-woocommerce/
https://www.webstudiobrana.com/wsb-hub3 )

Hvala.

**Comment by coax** [comment]
Bok, što si napisao u polja _Naslov poruke_ i _Sadržaj poruke_? Možeš poslati i putem tehničke podrške izravno iz Solo sučelja ako ne želiš javno. Moguće da je neki čudan, nepodržani znak spriječio spremanje u bazu.

Dodana je podrška za iduće načine plaćanja/dodatke (**nisu testirani u produkciji**):
- [Croatian payment slip generator for WooCommerce](https://wordpress.org/plugins/croatian-payment-slip-generator-for-woocommerce/)
- [myPOS Checkout for WooCommerce](https://wordpress.org/plugins/mypos-virtual-for-woocommerce/)

Treba preuzeti [novi release](https://github.com/coax/solo-for-woocommerce/releases), otpakirati iz ZIP datoteke i samo kopirati u mapu preko starih datoteka, ne treba deaktivirati ili ponovno instalirati dodatak iz WordPress administracije.

**Comment by Doda89vk** [comment]
Napisao sam ime shopa - račun (naslov maila)

Sadržaj maila samo da se u privitku nalazi račun i zahvalio na kupovini. Od znakova se jedino nalaze slova naše abecede (č,ć...) te link na web shop.

**Comment by coax** [comment]
Svejedno bih molio da pošalješ od slova do slova tekst jer jedino tako mogu lokalno testirati i saznati uzrok.

Ili još bolje - pokušaj upisati neki drugi tekst u ta polja pa vidi hoće li spremiti.

**Comment by coax** [comment]
Uzrok problema bili su emojiji. Ako će netko imati sličan problem - nemojte upisivati emojije u polja Naslov ili Sadržaj 😉 😁
