### ISSUE TITLE
Opis proizvoda/usluge na računu s varijacijama

### ISSUE THREAD

**Issue by hrvac** [coax/solo-for-woocommerce#11]
Pozdrav,
trenutno plugin upisuje samo pod "Opis proizvoda/usluge" na računu ime proizvoda. Je li moguće da upisuje uz ime proizvoda na račun i varijacije koje je kupac odabrao (npr. boja, veličina, dimenzije itd...)? 
Primjer: Tenisice, plave, 43 broj

**Comment by coax** [comment]
Kada bi u dodatak dodali da ispisuje i nazive atributa (Boja i Veličina), izgledalo bi ovako na računu pod "Opis proizvoda/usluge":
```
Tenisice - plava, 43
Boja: plava
Veličina: 43
```
Smatram da bi to bilo loše rješenje. WooCommerce nažalost nema opciju da se iz naziva varijabilnog proizvoda ukloni sufiks " - plava, 43".

**Comment by coax** [comment]
To već funkcionira na taj način. Na računu će pisati "Tenisice - plava, 43"

**Comment by hrvac** [comment]
Kod mene ne radi, ispisuje mi samo naziv proizvoda, ne i varijacije.

**Comment by coax** [comment]
Otkrio sam razlog - u tvom slučaju ne prikazuje jer varijacije nemaju vlastitu cijenu i WooCommerce ih ne sprema u nazivu nego odvojeno, u meta tagovima. Objavljena je nova verzija i sada će prikazati varijacije na računu/ponudi.

**Comment by hrvac** [comment]
Ovako mi sada prikazuje na računu:

Ime proizvoda
Pa_dimenzije: 40x50-cm
Pa_paspartu: s-paspartuom

**Comment by hrvac** [comment]
Atributi su definirani na Dashboard > Proizvodi > Atributi

![atri2](https://github.com/user-attachments/assets/57602f3e-ea43-4897-bc7b-cb0ea4d99aec)
![atri3](https://github.com/user-attachments/assets/51c4a69a-6a52-4859-88ad-6a484b52c71d)

Ovdje je slika kako povlačim atribute na određenom proizvodu. Dakle, ne radim ih u samom prozvodu već ih povlačim iz administracije.
![atri1](https://github.com/user-attachments/assets/4f39a389-46bc-42c4-a8be-9b62c2ab4f9b)

**Comment by coax** [comment]
A gdje definiraš cijene za atribute/vrijednosti ako je proizvod varijabilan?

**Comment by hrvac** [comment]
Evo screenshot 
![atri4](https://github.com/user-attachments/assets/68eb23fe-738b-4428-a93e-1576df2271f3)

**Comment by coax** [comment]
U _solo-woocommerce.php_ datoteci nađi:
```
// Variable item
if ($item['variation_id']) {
	// Replace order item name with product name
	$item_name = $product->get_title();

	// Append attributes and variations to product name
	$item_meta_data = $item->get_meta_data();
	foreach ($item_meta_data as $meta_data) {
		$meta_data_as_array = $meta_data->get_data();
		$item_name .= '\r\n' . esc_html(ucfirst($meta_data_as_array['key']) . ': ' . $meta_data_as_array['value']);
	}
}
```
i zamijeni s ovim:
```
// Variable item
if ($item['variation_id']) {
	// Replace order item name with product name
	$item_name = $product->get_title();

	// Append attributes and variations to product name
	foreach ($item->get_meta_data() as $meta) {
		if (empty($meta->id) || '' === $meta->value || !is_scalar($meta->value)) {
			continue;
		}

		$meta->key = rawurldecode((string) $meta->key);
		$meta->value = rawurldecode((string) $meta->value);
		$attribute_key = str_replace('attribute_', '', $meta->key);
		$display_key = wc_attribute_label($attribute_key, $product);
		$display_value = wp_kses_post($meta->value);

		if (taxonomy_exists($attribute_key)) {
			$term = get_term_by('slug', $meta->value, $attribute_key);
			if (!is_wp_error($term) && is_object($term) && $term->name) {
				$display_value = $term->name;
			}
		}
		$item_name .= '\r\n' . $display_key . ': ' . $display_value;
	}
}
```
Javi kako je prošlo.

**Comment by hrvac** [comment]
Promijenio sam kod. Sada se na računu prikazuje ovako:

Ime proizvoda
Ime atributa 1: Varijacija xx
Ime atributa 2: Varijacija yy

Može li se kod prilagoditi da piše ovako:

Ime proizvoda, varijacija xx, varijacija yy ?

**Comment by coax** [comment]
Može, umjesto:
```
		$item_name .= '\r\n' . $display_key . ': ' . $display_value;
```
stavi ovo:
```
		$item_name .= ', ' . $display_value;
```

**Comment by hrvac** [comment]
Hvala puno, radi izvrsno!
