### ISSUE TITLE
Tip usluge nije poslan ili u neispravnom formatu.

### ISSUE THREAD

**Issue by CastrumS** [coax/solo-for-woocommerce#2]
Pozdrav,

nakon označavanje narudžbe kao Završene/Completed Solo u Arhiva tabu javlja ovu grešku kao API odgovor:
"status": 103,
"message": "Tip usluge nije poslan ili u neispravnom formatu."

Kako ovo mogu popraviti? Mogu poslati Woo status ako je to potrebno.

Hvala.

**Comment by CastrumS** [comment]
Hvala, koristim verziju 1.1 i dodavanje tipa usluge (1) je pomoglo.

Međutim sad mi plugin izbacuje novu grešku:
"status": 113,
"message": "Porezna stopa nije poslana ili u neispravnom formatu."

Porezna stopa je postavljena i u Woocommerce-u i u Solo-u.

**Comment by coax** [comment]
Pejstaj log ovdje da vidim što se šalje na Solo. Možda je zaista neispravna porezna stopa.

**Comment by CastrumS** [comment]
<html>
<body>

POST https://api.solo.com.hr/racun
token=*****************************c06f
&tip_usluge=1
&prikazi_porez=1
&tip_racuna=1
&kupac_naziv=XXXXXX+XXXXXX
&kupac_adresa=XXXXXX+XX+10000+Zagreb%2C+HR
&kupac_oib=
&usluga=1
&opis_usluge_1=Test+Proizvod
&jed_mjera_1=1
&cijena_1=2,00
&kolicina_1=1
&popust_1=50
&porez_stopa_1=
&usluga=2
&opis_usluge_2=Po%C5%A1tarina
&jed_mjera_2=1
&cijena_2=4,00
&kolicina_2=1
&popust_2=0
&porez_stopa_2=0
&nacin_placanja=1
&iban=1
&jezik_racuna=1
&fiskalizacija=0
--



</body>
</html>

&porez_stopa_1= - porezna stopa je prazna.

**Comment by coax** [comment]
WooCommerce proizvod ti ne sadrži porez. Rješenje je ili dodati porez tom proizvodu (npr. 0%) što će odmah proraditi ili pričekaj iduću verziju dodatka kroz dan-dva.

**Comment by CastrumS** [comment]
Pričekam sljedeću verziju plugina jer svi proizvodi koriste standardnu klasu poreza. Hvala!

**Comment by CastrumS** [comment]
Pozdrav,

s novom verzijom više nema errora i računi se kreiraju u Solo aplikaciji. Međutim, na sve račune se primjenjuje popust of 100% - "usluge": [
{
"broj": "1",
"opis_usluge": "Test Proizvod",
"jed_mjera": "-",
"kolicina": "1",
"cijena": "0,80",
"popust": "100",
"porez_stopa": "25",
"suma": "0,00"
}
],

**Comment by CastrumS** [comment]
Update: do primjene 100% popusta dolazi kod kupnje proizvoda koji je već na sniženju kad se proizvod kupuje uz primjenu kupona za besplatnu dostavu.

Ako kupim proizvod koji je na sniženju bez kupona za besplatnu dostavu sve radi kako treba. Isto vrijedi i za kupnju proizvoda koji nije na sniženju, a na koji je primijenjen kupon za besplatnu dostavu.

**Comment by coax** [comment]
Klikni na taj kupon za besplatnu dostavu u WooCommerce administraciji i provjeri da nemaš možda upisano _Coupon amount: 100_ jer će to i u košarici staviti popust 100% na sve artikle. Za besplatnu dostavu trebaš ostaviti _Coupon amount: 0_ i samo uključiti kvačicu na _Allow free shipping_.

**Comment by CastrumS** [comment]
Kupon je već tako postavljen. _Coupon amount_ je 0 i označen je _Allow free shipping_.

**Comment by coax** [comment]
Ispravljeno: https://github.com/coax/solo-for-woocommerce/releases/download/v1.1/solo-for-woocommerce.zip

**Comment by CastrumS** [comment]
Hvala! Sve radi.

Pitanje - jeste li možda u budućnosti mislili pokriti i dio sa poklon proizvodima(npr. YITH ili Woo Discount Rules)? Trenutno su iskazane pune cijene tih proizvoda bez obzira na to što su na webu prikazani kao besplatni jednom kad se dodaju u košaricu.

**Comment by coax** [comment]
Nije u planu uvođenje podrške za 3rd party WooCommerce dodatke.
