### ISSUE TITLE
Fatal error kod mijenjanja statusa narudžbe u "Završeno" kod plaćanja "Uplata na žiro račun"

### ISSUE THREAD

**Issue by jurica-zecevic** [coax/solo-for-woocommerce#3]
Pozdrav,

Postavke:
![image](https://github.com/coax/solo-for-woocommerce/assets/51235635/7a980d67-ed29-42bc-9c5d-cdc93c77adcb)

Greška kod mijenjanja statusa.
Fatal error: Uncaught TypeError: round(): Argument #1 ($num) must be of type int|float, array given in /home/elektronikcomhr/public_html/wp-content/plugins/solo-for-woocommerce/solo-woocommerce.php:686 Stack trace: #0 /home/elektronikcomhr/public_html/wp-content/plugins/solo-for-woocommerce/solo-woocommerce.php(686): round(Array) #1 /home/elektronikcomhr/public_html/wp-includes/class-wp-hook.php(326): solo_woocommerce->solo_woocommerce_process_order(20819, 'narudzba-poslan...', 'completed') #2 /home/elektronikcomhr/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) #3 /home/elektronikcomhr/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #4 /home/elektronikcomhr/public_html/wp-content/plugins/woocommerce/includes/class-wc-order.php(405): do_action('woocommerce_ord...', 20819, 'narudzba-poslan...', 'completed', Object(WC_Order)) #5 /home/elektronikcomhr/public_html/wp-content/plugins/woocommerce/includes/class-wc-order.php(253): WC_Order->status_transition() #6 /home/elektronikcomhr/public_html/wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-data.php(714): WC_Order->save() #7 /home/elektronikcomhr/public_html/wp-includes/class-wp-hook.php(326): WC_Meta_Box_Order_Data::save(20819) #8 /home/elektronikcomhr/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) #9 /home/elektronikcomhr/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #10 /home/elektronikcomhr/public_html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-meta-boxes.php(263): do_action('woocommerce_pro...', 20819, Object(WP_Post)) #11 /home/elektronikcomhr/public_html/wp-includes/class-wp-hook.php(326): WC_Admin_Meta_Boxes->save_meta_boxes(20819, Object(WP_Post)) #12 /home/elektronikcomhr/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) #13 /home/elektronikcomhr/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #14 /home/elektronikcomhr/public_html/wp-includes/post.php(4760): do_action('save_post', 20819, Object(WP_Post), true) #15 /home/elektronikcomhr/public_html/wp-includes/post.php(4862): wp_insert_post(Array, false, true) #16 /home/elektronikcomhr/public_html/wp-admin/includes/post.php(453): wp_update_post(Array) #17 /home/elektronikcomhr/public_html/wp-admin/post.php(227): edit_post() #18 {main} thrown in /home/elektronikcomhr/public_html/wp-content/plugins/solo-for-woocommerce/solo-woocommerce.php on line 686

**Comment by jurica-zecevic** [comment]
WooCommerce Inačica 8.2.2
WordPress Inačica 6.4.3

**Comment by coax** [comment]
Ispravljeno. Preuzmi novu verziju: https://github.com/coax/solo-for-woocommerce/releases/download/v1.1/solo-for-woocommerce.zip

**Comment by jurica-zecevic** [comment]
Hej. 
Hvala na brzom odgovoru.
Sa novom verziojom ne baca grešku, kreirao se novi račun u Solo-u ali iznos računa je 0€
![image](https://github.com/coax/solo-for-woocommerce/assets/51235635/8b944e92-d12f-4220-aa62-ff3e9293ca2d)

**Comment by coax** [comment]
Kopipejstaj mi "API zahtjev" iz Arhive.

**Comment by coax** [comment]
Nepotrebno, vjerojatno si imao artikl s popustom. Preuzmi novu verziju: https://github.com/coax/solo-for-woocommerce/releases/download/v1.1/solo-for-woocommerce.zip

**Comment by jurica-zecevic** [comment]
Pozdrav,
Probao sa novom verzijom:
![image](https://github.com/coax/solo-for-woocommerce/assets/51235635/9819c142-84ca-4788-bf3b-643e48db07e3)

**Comment by coax** [comment]
Pošalji API zahtjev da vidim je li poslan popust. Ako nije, kakav je to artikl? Simple, complex, variable? Ima li popust?

**Comment by jurica-zecevic** [comment]
@coax Odustajem. Nije mi problem raditi ručno račune. Hvala na vremenu i pomoći :)
