### ISSUE TITLE
Solo ne nudi plaćanje pouzećem kao opciju

### ISSUE THREAD

**Issue by jurica-zecevic** [coax/solo-for-woocommerce#4]
Postavke Woocommerce-a:
![image](https://github.com/coax/solo-for-woocommerce/assets/51235635/cc1a8717-b0e6-4413-89e8-9d6bba099702)

Postavke Solo plugina:
![image](https://github.com/coax/solo-for-woocommerce/assets/51235635/a4902a20-2dcb-4bdb-8f3c-96d07bb971d0)

WooCommerce Inačica 8.2.2
WordPress Inačica 6.4.3

**Comment by coax** [comment]
Pozdrav, naš dodatak podržava samo načine plaćanja koji su navedeni [ovdje](https://github.com/coax/solo-for-woocommerce#na%C4%8Dini-pla%C4%87anja). Koliko vidim iz slike, ne koristiš WooCommerce plaćanje pouzećem već GLS? Kako se zove taj dodatak od GLS koji imaš instaliran?

**Comment by jurica-zecevic** [comment]
Pozdrav, popis sam već vidio... Koristim Woocomerce plaćanje pouzećem, samo je label drugi...

**Comment by coax** [comment]
Koji je ti link prikazan u dnu browsera kada se pređe mišem preko "Plaćanje pouzećem - Pouzeće (GLS)" u WooCommerce? Zanima me samo ono iza upitnika npr. _?page=wc-settings&tab=checkout&section=bacs_

**Comment by jurica-zecevic** [comment]
?page=wc-settings&amp;tab=checkout&amp;section=cod

**Comment by coax** [comment]
Ne znam zašto se ne prikazuje. Dodatak je namješten da prikaže "cod" način plaćanja tako da nije do nas.

**Comment by jurica-zecevic** [comment]
Pozdrav. Jeste li testirali na verzijama koje sam poslao?

**Comment by coax** [comment]
Dodatak se uvijek testira s najnovijom verzijom WooCommerce (trenutno je to 8.5.2). Nije moguće testirati sve verzije.
