### ISSUE TITLE
Pomoć ako je moguće

### ISSUE THREAD

**Issue by Mrki-vk** [coax/solo-for-woocommerce#5]
Poštovani
Hvala Vam prvo za ovaj besplatni plugin koji štedi jako mnogo vremena čak i u poluispravnom stanju.
Imam jedan sitni problem.
Na web trgovini imam plugin Woocommerce Custom Product Addons (5.x.x)
On mi daje opciju dodatne prodaje nekih djelova uz sami proizvod kao dodatna opcija.
Prilikom kupovine racun koji mi plugin napravi jer bez dodatnih opcija, bude bazicna cijena proizvoda a ne ukupno sve sto je uz taj proizvod kupljeno. Da Vam bude jasnije mozete pogledati na našoj web trgovini o ćem se radi na ovome linku:
https://ukrasizatorte.eu/proizvod/toper-sveta-potvrda-golubica/
Dali ima pomoći ili je to tako?
I ovako nam dosta pomaže jer nas spasi pisanja racuna, u ovoj opciji bi morali samo cijenu izmijeniti.
Unaprijed hvala na odgovoru!!
Davor

**Comment by coax** [comment]
Pozdrav, sve jasno, ali nažalost nismo u mogućnosti prilagođavati dodatak da radi s drugim dodacima, to bi otvorilo pandorinu kutiju i usporilo/otežalo daljnji razvoj.
Savjetovao bih da angažirate svog programera koji bi uzeo izvorni kod našeg dodatka i ubacio potrebne linije koda koje će prepoznati modifikacije u nardužbi od Custom Product Addons dodatka.

**Comment by Mrki-vk** [comment]
Hvala Vam puno na brzom odgovoru.
Snaći ćemo se.
