### ISSUE TITLE
Ne radi automatsko slanje računa

### ISSUE THREAD

**Issue by lightartdoo** [coax/solo-for-woocommerce#6]
Pozdrav , 

nakon konfiguracije svega nikako ne mogu dobiti da mi šalje automatski račun kupcu. 

Prilikom instalacije javilo se : The plugin does not have a valid header. 
ali plugin je tamo i radi. Synca sa solom i radi račune i za wire transfer i za stripe. 

WP Mail SMTP je konfiguriran i testiran, podaci od maila su na solu i rade.. 
Testiram sa wire transfer računima jer nisam stavio token za fiskalizaciju.  

Neka ideja ? :D

**Comment by coax** [comment]
Pozdrav, možeš li provjeriti u postavkama plugina je li uključeno da šalje mailove? Potrebno je imati upisan naslov i sadržaj poruke uz uključenu kvačicu da šalje automatski. Također, ne smiju biti emojiji u poruci.

**Comment by lightartdoo** [comment]
Pozdrav ,

Naravno da je uključeno slanje mailova...
Sve ostalo navedeno također...

**Comment by coax** [comment]
U administraciji dodatka, u sekciji "Arhiva", piše li da je poslan mail?

**Comment by coax** [comment]
U dodatku, u sekciji Arhiva, za neku od narudžbi koje su uspješno poslane u Solo, u zadnjoj kolumni "Datum slanja", piše li tamo datum i vrijeme ili "–"?

**Comment by lightartdoo** [comment]
Nema datuma ni vremena samo je "–".
Isprike nisam skužio opće tu rubriku na laptopu mi je van ekrana ispalo....

**Comment by coax** [comment]
Predlažem sljedeće:
1. u _wp-config.php_ dodati ove linije koda i zatim napraviti narudžbu da se pošalje u Solo te vidjeti u datoteci _/wp-content/debug.log_ je li došlo do kakve greške.
```
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
define( 'WP_DEBUG_DISPLAY', false );
```

2. umjesto "WP Mail SMTP" dodatka instalirati "[SMTP Mailer](https://wordpress.org/plugins/smtp-mailer/)" dodatak i napraviti narudžbu.

**Comment by lightartdoo** [comment]
PHP Deprecated:  Creation of dynamic property solo_woocommerce::$plugin_name is deprecated in /home/............/public_html/wp-content/plugins/solo-for-woocommerce/solo-woocommerce.php on line 297

**Comment by coax** [comment]
Ta greška nije vezana uz slanje mailova. Ima li koja druga greška nakon što je kreiran novi račun ili ponuda? Jesi li isprobao s drugim dodatkom koji sam predložio?

**Comment by lightartdoo** [comment]
Ma probao sam oba, nema drugih grešaka.... 
Niš mi ne pada na pamet, vjerojatno je neka glupost. 
Prije nego sam se javio sam 6 sati pokušavao....

**Comment by coax** [comment]
Predlažem da mi kreiraš kor. račun u svom WordPressu i pošalješ preko tehničke podrške ili mailom (bok@solo) kako bih pogledao o čemu se radi.

**Comment by lightartdoo** [comment]
treba ti admin acc pretpostavljam ili ?

**Comment by coax** [comment]
Da, kreiraj privremeno za potrebe testiranja. I napravi backup, za svaki slučaj.

**Comment by lightartdoo** [comment]
može, pošaljem ti na mail ubrzo. 
Tnx

**Comment by coax** [comment]
U wp-config.php datoteci (od WordPressa) je bila konstanta `define('DISABLE_WP_CRON', true);`. Nakon isključivanja te opcije je proradilo automatsko slanje mailova.

U iduću verziju dodatka ćemo dodati provjeru i obavijest za korisnike da isključe to.
