### ISSUE TITLE
Kartično plaćanje uspješno provedeno preko Stripea, račun nije kreiran

### ISSUE THREAD

**Issue by PostarLakogSna** [coax/solo-for-woocommerce#7]
Kao što stoji u naslovu, Kartično plaćanje uspješno provedeno preko Stripea, a račun u Solu nije kreiran. U tabu Arhiva stoji: Još niti jedna narudžba nije poslana u Solo.

Pod tabom načini plaćanja i akcije, stoji kao mogućnost samo uplata na žiro račun. Koristim DIVI temu. Plaćanje kreditnim karticama je očito omogućeno.

Provjere API tokena vraća sljedeće: Ispravan API token za korisnika xxxxx
Koristiš besplatni paket (ograničenje na 3 računa i ponude).

Dodatno, kako mogu izbaciti polje Trebam R1 račun?

**Comment by coax** [comment]
Pozdrav, iz opisanog mogu jedino pretpostaviti da koristiš neki drugi dodatak (plugin) za Stripe umjesto onog koji je integriran u WooCommerce. Provjeri u WooCommerce > Settings > Payments.

Trebam R1 se ne može isključiti u opcijama dodatka.

**Comment by PostarLakogSna** [comment]
Ovo je Plugin koji koristim: https://en-gb.wordpress.org/plugins/woo-stripe-payment/

**Comment by coax** [comment]
Naš dodatak ne prepoznaje taj plugin i zato nije prikazan u "Načini plaćanja i akcije" i zato ne kreira račun u Solo. Nažalost, nismo u mogućnosti dodati podršku za taj plugin jer on nudi nekoliko načina plaćanja odjednom i naš dodatak ne bi znao što treba, a što ne fiskalizirati. Predlažem da se koristi službeni dodatak [Stripe for WooCommerce](https://woocommerce.com/products/stripe/) za naplatu kreditnim karticama.
