### ISSUE TITLE
Greška prlikom aktivacije plugin-a

### ISSUE THREAD

**Issue by Doda89vk** [coax/solo-for-woocommerce#8]
Ovdje sam preuzeo zadnju verziju, instaliram dodatak i kada ga želim aktivirati dobijem pogrešku: "**Dodatak nema ispravno zaglavlje.**"

**Comment by coax** [comment]
Ta greška se javlja kad WordPress ne može dohvatiti informacije o dodatku iz zaglavlja glavne datoteke. Izgleda da možda imaš nepotpunu instalaciju - vjerojatno nije dobro otpakirana arhiva ili je došlo do oštećenja datoteka pri otpakiravanju ili nije dobro uploadano na poslužitelj. Predlažem da obrišeš dodatak, ponovno preuzmeš i ponovno instaliraš + aktiviraš,
