### ISSUE TITLE
Ne prepoznaje plaćanje po pouzeću

### ISSUE THREAD

**Issue by hrvac** [coax/solo-for-woocommerce#9]
Imam problem s prepoznavanjem plaćanja po pouzeću u administraciji plugina.
Naime, on se prikazuje u administraciji plugina samo onda kada je opcija "Prihvati virtualne narudžbe" uključena. Nakon što se ta opcija ugasi, u administraciji plugina više nema plaćanja pouzećem.

**Comment by coax** [comment]
Prikazuje li ti se opcija plaćanja pouzećem (s isključenom opcijom prihvata virtualnih narudžbi) u trgovini kada ideš na checkout?

**Comment by hrvac** [comment]
Checkout normalno radi jer mi je stalno isključena opcija prihvata virtualnih narudžbi za plaćanje po pouzeću. Problem je što ovaj plugin ne prepooznaje opciju plaćanja pouzećem dok je isključen prihvat virtualnih narudžbi na plaćanju po pouzeću.

**Comment by coax** [comment]
Možeš li poslati screenshot svoje checkout stranice gdje se vidi da je ponuđeno plaćanje pouzećem za proizvod koji nije virtualan?

**Comment by hrvac** [comment]
Evo u privitku
![narud](https://github.com/user-attachments/assets/fac7a0cd-f18b-4177-9711-4cfce25867b8)

**Comment by coax** [comment]
Hvala. Uključene/aktivne načine plaćanja naš dodatak dobiva direktno od WooCommerce plugina i ne znam zašto ne šalje "Plaćanje pouzećem" kada je onemogućen prihvat virtualnih narudžbi. Jedino rješenje za ovo je da se u datoteci /lib/solo-for-woocommerce.php na liniji 227 zamijeni
`$gateways = WC()->payment_gateways->get_available_payment_gateways();`
s
`$gateways = WC()->payment_gateways->payment_gateways();`

Tada će biti prikazani svi načini plaćanja iz WooCommerce (aktivni ili ne).

**Comment by coax** [comment]
Preuzeti novu verziju dodatka gdje je implementirana ova metoda.
